GET http://{{host}}/api/v1/devices
Accept: application/json
Authorization: Bearer {{token}}

###
POST http://{{host}}/api/v1/device
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "tv",
  "buyAt": "2019-10-10",
  "category": 1,
  "price": 99
}

###

