name: Go
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

      - name: Check out code into the Go module directory
        uses: actions/checkout@v1
      - uses: actions/cache@v1
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Set up Go 1.13
        uses: actions/setup-go@v1
        with:
          go-version: 1.13
        id: go
      - name: Go Env
        run: go env

      - name: Launch MongoDB
        run: |
          docker-compose -f docker-compose.test.yml up -d

      - name: Sleep
        uses: jakejarvis/wait-action@master
        with:
          time: '60s'

      - name: Check running containers
        run: docker ps

      - name: Get dependencies
        run: |
          go mod vendor

      - name: Test
        run: go test -v -cover ./...

      - name: Build
        run: go build -v .

